apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  - image: almalinux:9
    name: almalinux
    command: ["sleep", "1000"]
    volumeMounts:
    - mountPath: /cache/nginx-logs
      name: nginx-logs  
      readOnly: true    #almalinux can only read the logs 
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 100Mi