apiVersion: v1
kind: Pod
metadata: 
  name: error-test

spec:
  containers:
  - name: nginx
    image: ngindnsdl
#Error from server (BadRequest): error when creating "05-errors.yaml": Pod in version "v1" cannot be handled as a Pod: strict decoding error: unknown field "spec.conatiners"


    