apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    imageregistry: "https://hub.docker.com/"
    jenkins.url: "https://jenkins"
spec:
  containers:
  - name: nginx
    image: nginx 

