apiVersion: v1
kind: Pod
metadata:
  name: secrets-demo
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: pod-secret-config #name of the metadata in secrets 
