apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service

spec:
  selector:
    project: roboshop
    component: frontend
    purpose: clusterIP

  ports:
    - protocol: TCP
      port: 80 #service port - clusterIPport
      targetPort: 80
