apiVersion: v1
kind: Service
metadata:
  name: nodeport-service

spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    purpose: nodeport

  ports:
    - protocol: TCP
      port: 80 #service port - clusterIPport
      targetPort: 80
