apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service

spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    purpose: loadbalancer

  ports:
    - protocol: TCP
      port: 80 #service port - clusterIPport
      targetPort: 80
      nodePort: 30001
